HOME = "/data/nfs/analysis/interns/mfrohmann/deepfake-detector/"
POS_DB_PATH = HOME + "/data/real"
NEG_DB_PATH = HOME + "/data/fake/128/0"
CODEC_DB_PATH = HOME + "/fma_codec/"
WEIGHTS_PATH = HOME + "/weights/final/128"
RESULT_PATH = HOME + "/results/final/128"
SPLIT_PATH = HOME + "/data/dataset_medium_split.npy"
CONF_PATH = HOME + "/conf"
